AllCops:
  Exclude:
    - '**/Guardfile'
    - '**/Rakefile'
    - '**/Gemfile'
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/factories/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'node_modules/**/*'
    - 'bin/**/*'

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets
