version: "3.7"
services:
  www:
    build: .
    ports:
      - "3000:3000"
    security_opt:
      - seccomp="spec/chrome-seccomp.json"
    environment:
      DATABASE_HOST: db
    depends_on:
      - db
  db:
    image: postgres:10
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: ""
      POSTGRES_DB: findmyflock_development
