# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.4.3-node-browsers
        environment:
          RAILS_ENV: test
          BUNDLE_PATH: vendor/bundle
          PGUSER: root
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/postgres:10.4
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: findmyflock_test

    working_directory: ~/findmyflock/www

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: install dependencies
          command: |
            bundle check || bundle install
            yarn install

      - save_cache:
          paths:
            - vendor/bundle
            - ./node_modules
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          - v1-dependencies-{{ checksum "package.json" }}

      # Database setup
      - run:
          command: bundle exec rake db:create db:schema:load

      # run tests!
      - run:
          name: run tests
          command: bundle exec rspec
